using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace NotebookAppApi.Model
{
    public class Note
    {
        [BsonId]
        // standar BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        //external Id, easier to reference: 1,2,3 or A, B, C etc.
        public string Id { get; set; }

        public string body { get; set; } = string.Empty;

        [BsonDateTimeOptions]
        //atribute to gain control on datetime serialization
        public DateTime UpdateOn { get; set; } = DateTime.Now;

        public NoteImage HeaderImage { get; set; }

        public int UserId { get; set; } = 0;
    }
}
